### ISSUE TITLE
add plugin to QIIME 2 library

### ISSUE THREAD

**Issue by tkosciolek** [bioinf-mcb/q2-predict-dysbiosis#1]
https://library.qiime2.org/plugins/

**Comment by FFranciscoEspinosa** [comment]
When we try to use predict-dysbiosis with the files in the test_data there were two issues:
1. After the instruction: 
qiime predict-dysbiosis calculate-index --i-table test_files/taxonomy.qza --i-pathways-stratified test_files/pathways_stratified.qza --i-pathways-unstratified test_files/pathways_unstratified.qza --o-dysbiosis-predictions results.qza
there was an issue with a missing data directory. We place it manually and then we have the next issue:
2. After the same instruction that we use in 1. we have an code error, it seems that an array is empty.

The errors mesagge errors are below
[issue1.log](https://github.com/bioinf-mcb/q2-predict-dysbiosis/files/15204436/issue1.log)
[issue2.log](https://github.com/bioinf-mcb/q2-predict-dysbiosis/files/15204437/issue2.log)

We use 
Python version: 3.8.15
QIIME 2 release: 2023.7
QIIME 2 version: 2023.7.0
q2cli version: 2023.7.0
running in ubuntu inside windows

**Comment by Kizielins** [comment]
Hi @FFranciscoEspinosa, sorry to hear that - I'll have a look and get back to you.

**Comment by Kizielins** [comment]
Hi @FFranciscoEspinosa, sorry for taking that long - I struggled with finding the issue. I've now moved the script to a new repo - should be easier to run. Let me know if you still have issues!

https://github.com/Kizielins/q2-predict-dysbiosis/tree/master

**Comment by FFranciscoEspinosa** [comment]
It works well. Thank you so much.
